language: cpp
compiler:
  - gcc
before-install: sudo apt-get update -qq
install: sudo apt-get install -qq libboost-all-dev
before-script: mkdir build && cd build && cmake ../
script: cd build && make
