language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq libboost1.55-all-dev texlive texlive-latex-base latex-xcolor texlive-latex-extra g++-4.8
  - export CXX="g++-4.8" CC="gcc-4.8"
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - g++ --version
before_script: mkdir build && cd build && cmake ../
script: cd build && make
