#!/usr/bin/env ruby

require 'bio'
require 'optparse'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: example.rb [options] [paths]"

  opts.on("-p", "--[no-]path", "Display path column. Defaults to off when only one path argument given, and on otherwise.") do |v|
    options[:path] = v
  end
end.parse!

show_paths = ARGV.size > 1
if options.has_key?(:path)
  show_paths = options[:path]
end

ARGV.each{|path|
  prefix = ""
  prefix = path + "\t" if show_paths
  z = 0
  n = 0
  Bio::FastaFormat.open(path).each{|entry|
    x = entry.seq.length
    z += x
    n += 1
    puts x.to_s + "\t" + prefix + entry.definition.gsub(/\t/, " ")
  }
  $stderr.puts [path, 1.0 * z / n].join("\t")
}

