# - Try to find LibGOOGLEPERFTOOLS
# Once done this will define
#  GOOGLEPERFTOOLS_FOUND - System has LibGOOGLEPERFTOOLS
#  GOOGLEPERFTOOLS_INCLUDE_DIRS - The LibGOOGLEPERFTOOLS include directories
#  GOOGLEPERFTOOLS_LIBRARIES - The libraries needed to use LibGOOGLEPERFTOOLS

 find_path(GOOGLEPERFTOOLS_INCLUDE_DIR NAMES lbfgs.h)
# find_path(GOOGLEPERFTOOLS_INCLUDE_DIR NAMES lbfgs.h PATHS ${CMAKE_INCLUDE_PATH})

find_library(TCMALLOC_LIBRARY NAMES tcmalloc)
find_library(PROFILER_LIBRARY NAMES profiler)
#  xml2 libxml2
#             HINTS ${PC_LIBXML_LIBDIR} ${PC_LIBXML_LIBRARY_DIRS} )

#if(TCMALLOC_LIBRARY_FOUND)
  set(GOOGLEPERFTOOLS_LIBRARIES ${TCMALLOC_LIBRARY} ${PROFILER_LIBRARY})
  #endif
set(GOOGLEPERFTOOLS_LIBRARIES ${TCMALLOC_LIBRARY} ${PROFILER_LIBRARY})
set(GOOGLEPERFTOOLS_INCLUDE_DIRS ${GOOGLEPERFTOOLS_INCLUDE_DIR} )

include(FindPackageHandleStandardArgs)
# handle the QUIETLY and REQUIRED arguments and set LIBGOOGLEPERFTOOLS_FOUND to TRUE
# if all listed variables are TRUE
find_package_handle_standard_args(GOOGLEPERFTOOLS DEFAULT_MSG
  GOOGLEPERFTOOLS_LIBRARIES GOOGLEPERFTOOLS_INCLUDE_DIR)


